<header id="entete">
	<h1><img id="logo-banniere" src="ressources/img/logo.png" alt="" title="" /><a href="index.php" tile="retour à l'accueil">Cahier de recettes de LaLicorne</a>
	</h1>
	<nav>
		<ul>
			<li>Entrées
				<ul>
					<li></li>
				</ul>
			</li>
			<li>Plats
				<ul>
					<li></li>
				</ul>
			</li>
			<li>Desserts
				<ul>
					<li></li>
				</ul>
			</li>
			<li>Boissons
				<ul>
					<li></li>
				</ul>
			</li>
			<li>Gâteaux
				<ul>
					<li></li>
				</ul>
			</li>
			<li>Glaces
				<ul>
					<li></li>
				</ul>
			</li>
			<li>Friandises
				<ul>
					<li></li>
				</ul>
			</li>
			<li>Non-comestible
				<ul>
					<li></li>
				</ul>
			</li>
		</ul>
	</nav>
</header>